version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kyrgyz-prokat-db
    restart: always
    environment:
      POSTGRES_DB: kyrgyzCrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: kyrgyz-prokat-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kyrgyzCrm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
      JWT_SECRET: H++w6Z2o20mZqgq0j9jNQX0Rz2aDqv4VQ6YH4xqU3Rk=
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
