spring.application.name=auth-service
server.port=8080
debug=true

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/kyrgyzCrm
spring.datasource.username=postgres
spring.datasource.password=123321
jwt.secret=H++w6Z2o20mZqgq0j9jNQX0Rz2aDqv4VQ6YH4xqU3Rk=
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

