-- Step 1: Drop foreign key constraints
ALTER TABLE rental_documents DROP CONSTRAINT IF EXISTS fk_rental_documents_tool_id;
-- Step 2: Add new BIGINT columns
ALTER TABLE tool_instances ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE rental_documents ADD COLUMN new_tool_id BIGINT;

-- Step 3: Update rental_documents with new tool_id
UPDATE rental_documents rd
SET new_tool_id = ti.new_id
FROM tool_instances ti
WHERE rd.tool_id = ti.id;

-- Step 4: Drop old UUID columns and rename new ones
ALTER TABLE tool_instances DROP COLUMN id CASCADE;
ALTER TABLE tool_instances RENAME COLUMN new_id TO id;
ALTER TABLE tool_instances ADD PRIMARY KEY (id);

ALTER TABLE rental_documents DROP COLUMN tool_id;
ALTER TABLE rental_documents RENAME COLUMN new_tool_id TO tool_id;

-- Step 5: Recreate foreign keys
-- Assuming tool_id in rental_documents is nullable and just a logical reference or real FK
-- Let's check if it was a real FK in V6/V1
-- We'll add it if it makes sense, though RentalDocument just maps toolId as UUID without a direct @ManyToOne usually, wait:
-- In RentalDocument: @Column(name = "tool_id") private Long toolId;
-- There is @OneToMany(mappedBy = "contract") in RentalDocument for tools, so ToolInstance has:
-- @ManyToOne @JoinColumn(name = "contract_id") private RentalDocument contract;
-- Oh wait, I didn't change contract_id! `contract_id` in `tool_instances` is still `BIGINT`, which is correct because `RentalDocument` id is `Long`.

-- So we just need to fix tool_id in rental_documents (which is a backward reference or something).

-- Wait, what about `tool_id` in `rental_document_tools`? 
-- There is no such table, ToolInstance has `contract_id`.

